### ISSUE TITLE
When you set more lives, it should be shown in the game (maybe with a number)

### ISSUE THREAD

**Issue by WolfmosRioja** [enriquesanchezb/game_for_testing#19]
<img width="1011" alt="Captura de pantalla 2023-11-22 a las 16 51 33" src="https://github.com/enriquesanchezb/game_for_testing/assets/25226013/a60a86c7-5ab7-4cd1-bef9-7feada289e16">

**Comment by enriquesanchezb** [comment]
Feature request!
