### ISSUE TITLE
When the dog is crouch is not possible to jump

### ISSUE THREAD

**Issue by asanchez1978** [enriquesanchezb/game_for_testing#4]
When the dog is agachao is not possible to jump

**Comment by enriquesanchezb** [comment]
Add a prober description or add a video or something like that!

**Comment by asanchez1978** [comment]
In order to reproduce it:
1. start the game
2.  press the down arrow
3. 3. press the up arrow
The dog not movws or jump.

**Comment by enriquesanchezb** [comment]
If you are down and push down the dog stays. It's a feature
